import { surfaceContracts, commonSurfaceContractOrder } from "./contracts";

function json(value: unknown) {
  return JSON.stringify(value, null, 2);
}

export function renderToolsSurfaceContractMarkdown() {
  const commonShapes = commonSurfaceContractOrder
    .map((surfaceType) => {
      const contract = surfaceContracts[surfaceType];
      return `- \`${surfaceType}\`: ${contract.requiredPaths
        .filter((path) => path.startsWith("payload.data."))
        .map((path) => `\`${path.replace("payload.", "")}\``)
        .join(", ")}`;
    })
    .join("\n");

  return [
    "## Chieflane Surface Tools",
    "",
    "### surface_publish",
    "Create or replace a persistent shell surface for work worth reopening later.",
    "",
    "### surface_patch",
    "Update an existing shell surface by `surfaceKey`.",
    "",
    "### surface_close",
    "Archive or close a shell surface once complete.",
    "",
    "## Chieflane Surface Payload Contract",
    "",
    "When calling `surface_publish`, `payload` must be an object. Do not send `payload` as a string.",
    "",
    "### Minimal valid `brief` example",
    "```json",
    json(surfaceContracts.brief.minimalExample),
    "```",
    "",
    "### Common shapes",
    commonShapes,
    "",
    "### Rules",
    "- `fallbackText` and `freshness.generatedAt` are always required.",
    "- `actions` are recommended for actionable surfaces, but can be empty for passive summaries or demo surfaces.",
    "- `sourceRefs` are recommended when summarizing email, calendar, docs, notes, CRM, or web research.",
    "- If uncertain, publish a minimal `brief` surface instead of improvising a more complex type.",
    "",
    "### Minimal `surface_patch` example",
    "```json",
    json({
      surfaceKey: "brief:example:2026-04-10",
      patch: {
        status: "done",
        summary: "The brief was reviewed.",
      },
    }),
    "```",
    "",
    "### Minimal `surface_close` example",
    "```json",
    json({
      surfaceKey: "brief:example:2026-04-10",
      finalStatus: "archived",
    }),
    "```",
    "",
  ].join("\n");
}

export function renderAgentsSurfaceLifecycleMarkdown() {
  return [
    "## Chieflane Shell Integration",
    "",
    "When persistent shell surfaces are available, use them for multi-step work, approvals, meeting prep, dossiers, drafts, digests, and queued follow-ups. Prefer updating existing surfaces by stable `surfaceKey` rather than creating duplicates.",
    "",
    "If `.chieflane/profile.md` exists, consult it when shaping Chieflane surfaces and summaries.",
    "",
    "## Chieflane Surface Lifecycle Rules",
    "",
    "Use shell surfaces when work is multi-step, approval-driven, likely to be reopened, or better represented as structured UI than plain text.",
    "",
    "### Publish",
    "Publish a new surface when the user will likely reopen it later, the work needs review or tracking, or it belongs in a lane like `today`, `meetings`, `drafts`, `people`, `research`, or `ops`.",
    "",
    "### Patch",
    "Prefer `surface_patch` over creating duplicates when the same work item is evolving, status changes, or new context arrives.",
    "",
    "### Close",
    "Close or archive a surface only after the work is complete, superseded, or no longer useful. Patch it to `done` first when appropriate.",
    "",
    "### Leave visible",
    "Do not close a surface that is still awaiting review, blocked, tied to an upcoming meeting, pending follow-up, or serving as a demo/test surface.",
    "",
    "### Default fallback",
    "If uncertain about shape or layout, publish a minimal `brief` surface rather than guessing a complex one.",
    "",
    "## Chieflane Programs",
    "",
    "### Program: Morning Ops",
    "Authority: prepare a morning brief and today board.",
    "Trigger: weekday cron.",
    "Approval gate: no external sends without review.",
    "",
    "### Program: Evening Wrap",
    "Authority: summarize the day, identify incomplete work, and prepare rollover.",
    "Trigger: weekday cron.",
    "Approval gate: summary is allowed; drafts require review.",
    "",
    "### Program: Weekly Exec Agenda",
    "Authority: compile the executive agenda for the upcoming week.",
    "Trigger: Sunday cron.",
    "Approval gate: publish planning surfaces only.",
    "",
    "### Program: Meeting Ops",
    "Authority: prepare meeting surfaces, extract decisions, create follow-up drafts, and update relationship context.",
    "Trigger: before/after meetings and explicit requests.",
    "Approval gate: drafts are allowed; sending requires review.",
    "",
    "### Program: Relationship Context",
    "Authority: maintain structured context on important people, companies, and projects.",
    "Trigger: after meetings, major threads, and weekly review.",
    "Approval gate: never invent facts.",
    "",
    "### Program: Weekly Kaizen",
    "Authority: identify repeated friction, propose improvements, and surface changes.",
    "Trigger: weekly cron.",
    "Approval gate: apply only with approval.",
  ].join("\n");
}

export function renderChiefShellSkillMarkdown() {
  return [
    "# chief-shell",
    "",
    "You have access to three shell tools:",
    "- `surface_publish` - create or replace a persistent shell surface",
    "- `surface_patch` - update fields on an existing surface",
    "- `surface_close` - archive or close a surface",
    "",
    "## When to publish a surface",
    "",
    "Use shell surfaces for work that is multi-step, approval-driven, likely to be reopened, better presented as structured UI than plain text, tied to people or meetings, or part of a recurring workflow.",
    "",
    "## When not to publish a surface",
    "",
    "Do not publish a surface for trivial acknowledgements, short confirmations, one-off factual answers, or work with no follow-up value.",
    "",
    "## Minimal valid example",
    "",
    "Use this exact shape when uncertain:",
    "",
    "```json",
    json(surfaceContracts.brief.minimalExample),
    "```",
    "",
    "## Common shapes",
    "",
    "### brief",
    "Required: `payload.surfaceType = \"brief\"`, `payload.data.headline`, `payload.data.sections[]`, `fallbackText`, `freshness.generatedAt`.",
    "Recommended: `actions[]`, `sourceRefs[]`, `priority`.",
    "",
    "### queue",
    "Required: `payload.surfaceType = \"queue\"`, `payload.data.emptyMessage`, `payload.data.items[]`, `fallbackText`, `freshness.generatedAt`.",
    "",
    "### board",
    "Required: `payload.surfaceType = \"board\"`, `payload.data.columns[]`, `fallbackText`, `freshness.generatedAt`.",
    "",
    "### composer",
    "Required: `payload.surfaceType = \"composer\"`, `payload.data.channel`, `payload.data.body`, `payload.data.recipients[]`, `fallbackText`, `freshness.generatedAt`.",
    "",
    "### prep / debrief",
    "Required: `payload.surfaceType`, `payload.data.summary`, `payload.data.attendees[]`, `fallbackText`, `freshness.generatedAt`.",
    "",
    "### dossier / digest",
    "Required: `payload.surfaceType`, the typed `payload.data` object, `fallbackText`, `freshness.generatedAt`.",
    "",
    "## Required vs recommended",
    "",
    "Always required:",
    "- `surfaceKey`",
    "- `lane`",
    "- `title`",
    "- `summary`",
    "- `payload`",
    "- `fallbackText`",
    "- `freshness.generatedAt`",
    "",
    "Recommended unless not applicable:",
    "- `actions`",
    "- `sourceRefs`",
    "- `entityRefs`",
    "- `priority`",
    "",
    "## Safe defaults",
    "",
    "When uncertain, use `brief`, lane `today`, status `ready`, priority `50`, `actions: []`, and `sourceRefs: []` unless the surface summarizes external material.",
    "",
    "## Lifecycle",
    "",
    "Reuse `surfaceKey` whenever possible. Prefer `surface_patch` over duplicates. Patch a surface to `done` before closing it when the work is complete. Leave surfaces visible while review, follow-up, or an upcoming meeting still matters.",
    "",
    "## Surface types",
    "",
    ...Object.values(surfaceContracts).map(
      (contract) =>
        `- \`${contract.surfaceType}\` - ${contract.purpose}`
    ),
    "",
    "## Freshness",
    "",
    "Always set `freshness.generatedAt` to the current timestamp. Add `expiresAt` when the surface is time-sensitive.",
  ].join("\n");
}
